version: '3'
services:
  status:
    image: klakegg/hugo:0.84.3-asciidoctor
    volumes:
      - .:/src
    ports:
        - 1313:1313
    command: "serve --cleanDestinationDir --disableFastRender --path-warnings --print-mem --verbose --verboseLog --noHTTPCache"
