policies:
  - name: Local Updatecli Website Policies
    config:
      - updatecli/updatecli.d/
  - name: Handle Nodejs version in githubaction
    policy: ghcr.io/updatecli/policies/nodejs/githubaction:0.7.0@sha256:5d88f7b90c3de3f3f73245918bdeaf78ff27365b8333c960788fdacfefbdc493
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/nodejs.yaml
  - name: Handle Nodejs version in Netlify
    policy: ghcr.io/updatecli/policies/nodejs/netlify:0.6.0@sha256:39b27410fe549742b4932b7e5f057617c59d204d1a1ae4064238ba4c016fe9a6
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/nodejs.yaml
  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/updatecli/autodiscovery:0.5.0@sha256:947817644fb89e27f7b7121b822328c2d47364c7a3a08241e4d2ac1a5897020c
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/compose.yaml
  - name: Handle HUGO version in netlify
    policy: ghcr.io/updatecli/policies/hugo/netlify:0.6.0@sha256:6a2e848a5f968d4547eb6c02be487bb027886b1699fbde49b7b0dcd32cc6aa33
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/hugo.yaml
  - name: Handle HUGO version in GitHub action
    policy: ghcr.io/updatecli/policies/hugo/githubaction:0.7.0@sha256:c7fda38c9b2117b49b8781061323083b1716fc68e5599ca699b1d3c6cc9fee5e
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/hugo.yaml
  - name: Handle NPM version in netlify
    policy: ghcr.io/updatecli/policies/npm/netlify:0.5.0@sha256:860b85310e7b9bdeced41b4fe251dfac3756a63a1991db826a4e7b70644c4a8c
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/npm.yaml
  - name: NPM autodiscovery
    policy: ghcr.io/updatecli/policies/npm/autodiscovery:0.7.0@sha256:4d7587d8570c25b02f9a9e9f580b1ff6e6790c0bd8dac29893043244ca038841
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/npm.yaml
  - name: Handle Updatecli version in GitHub action
    policy: ghcr.io/updatecli/policies/updatecli/githubaction:0.1.0@sha256:a5b8933ebfc65ba6ea9e60927900135062a3293f18a68292431cec1e53208e3d
    values:
      - updatecli/values.d/scm.yaml
