policies:
  - name: Local Updatecli Website Policies
    config:
      - updatecli/updatecli.d/
    values:
      - updatecli/values.d/scm.yaml

  - name: Handle Nodejs version in githubaction
    policy: ghcr.io/updatecli/policies/nodejs/githubaction:0.11.1@sha256:812c245adc1f20767ca912baf3087022c78e8153a3f27d43729dd8931864f8e3
    values:
      - updatecli/values.d/scm.yaml
    valuesinline:
      versionpattern: "~24"
      automerge: true

  - name: Handle Nodejs version in Netlify
    policy: ghcr.io/updatecli/policies/nodejs/netlify:0.10.1@sha256:3bc908b4bfc7c44cb4a1ff9c1cad0c61c16f37b9c8e45b50bd632eb05f54521f
    values:
      - updatecli/values.d/scm.yaml
    valuesinline:
      versionpattern: "~24"
      automerge: true

  - name: Handle HUGO version in netlify
    policy: ghcr.io/updatecli/policies/hugo/netlify:0.10.1@sha256:1f8e3c699605590da3f48ace142f46e10c21bbabbcf26864dcc7ad141dc359ab
    values:
      - updatecli/values.d/scm.yaml
    valuesinline:
      automerge: true

  - name: Handle HUGO version in GitHub action
    policy: ghcr.io/updatecli/policies/hugo/githubaction:0.11.1@sha256:44ced9f1f19b601502194b9c4d3400efb8cd54ea7ab5008b96902ad8ec931fee
    values:
      - updatecli/values.d/scm.yaml
    valuesinline:
      automerge: true

  - name: Handle NPM version in netlify
    policy: ghcr.io/updatecli/policies/npm/netlify:0.11.1@sha256:8fda888dd1e0ec3a4f855817529ece27472bbb77ab59f15dd2ee593df128e284
    values:
      - updatecli/values.d/scm.yaml
    valuesinline:
      automerge: true

  - name: NPM autodiscovery
    policy: ghcr.io/updatecli/policies/npm/autodiscovery:0.12.1@sha256:ab02848169d584d7510ab974ec4a27309d9737068b1d888df6a8388a3dad26fc
    values:
      - updatecli/values.d/scm.yaml
    valuesinline:
      automerge: true
      groupby: individual
      spec:
        ignoreversionconstraints: true

  - name: Handle Updatecli version in GitHub action
    policy: ghcr.io/updatecli/policies/updatecli/githubaction:0.8.1@sha256:48872bbf1a09cfff32ff5ffa07086c20b40d6888c19c36048b18f84bbdad37fe
    values:
      - updatecli/values.d/scm.yaml

  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/updatecli/autodiscovery:0.7.0@sha256:6890c4b4093a80063f518101881098fab8211c986481641faaf797a9ad5a31c3
    values:
      - updatecli/values.d/scm.yaml
    valuesinline:
      spec:
        files:
          - "updatecli-compose.yaml"
          - "updatecli-compose-release.yaml"
