policies:
  - name: Local Updatecli Website Policies
    config:
      - updatecli/updatecli.d/
  - name: Handle Nodejs version in githubaction
    policy: ghcr.io/updatecli/policies/nodejs/githubaction:0.10.0@sha256:66b180d6fc9bd157472b9adb564c4bfc5a9ce19d72faaa9ddd3e90b70f328d0e
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/nodejs.yaml
  - name: Handle Nodejs version in Netlify
    policy: ghcr.io/updatecli/policies/nodejs/netlify:0.8.1@sha256:a858208ad7fbdbe79bbe2f5f1a77a6c99d9e3efe0d3b474b8912646b203f4108
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/nodejs.yaml
  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/updatecli/autodiscovery:0.6.1@sha256:71ce3cf69ebf8b7c25fa6131c51de2e13ceef9b832a4689b9d9422c7ce03bef1
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/compose.yaml
  - name: Handle HUGO version in netlify
    policy: ghcr.io/updatecli/policies/hugo/netlify:0.8.1@sha256:ce9874efc1824f532cc4389b82e209b41b97b5eabd6a3ad10a649890cf353fdd
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/hugo.yaml
  - name: Handle HUGO version in GitHub action
    policy: ghcr.io/updatecli/policies/hugo/githubaction:0.9.1@sha256:36dc28dda540eeff0a453cefdc8a726a4edf12068867a6b5660d6592dc4c3669
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/hugo.yaml
  - name: Handle NPM version in netlify
    policy: ghcr.io/updatecli/policies/npm/netlify:0.9.1@sha256:99b2cd55f46d998158997e590514306a8c5de0650c1fce13cba62008e2327d08
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/npm.yaml
  - name: NPM autodiscovery
    policy: ghcr.io/updatecli/policies/npm/autodiscovery:0.10.1@sha256:4a7f65caa5339753d09d5b57e288d42c411a3cace8cb0d2e4c41c36a29e5d830
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/npm.yaml
  - name: Handle Updatecli version in GitHub action
    policy: ghcr.io/updatecli/policies/updatecli/githubaction:0.6.0@sha256:b7ab820e0203221ca5c529442940263f97b597613a27b7056ab3455815853d2b
    values:
      - updatecli/values.d/scm.yaml
