policies:
  - name: Local policies
    config:
      - updatecli/updatecli.d/
    values:
      - updatecli/values.d/scm.yaml

  - name: Trigger releasepost
    policy: ghcr.io/updatecli/policies/releasepost/releasepost:0.11.1@sha256:2158682cd91c63f29f59654a937dfd4906db9d3e678b5624067a2bdafe9f0c9b
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/releasepost.yaml
