services:
  db:
    image: postgres:18@sha256:5a5a84b19854a9ffaa54082c166ff4ec27473a361e496e5ea167f298f2da9722
    restart: always
    environment:
      - POSTGRES_USER=udash
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=udash
    expose:
      - 5432

  server:
    image: ghcr.io/updatecli/udash:v0.19.1@sha256:45e2285583879ef356e8138b14776defb6e42c3242b9b4fdfa07eb286d1ec03b
    command: server start
    restart: always
    environment:
      - GIN_MODE=release
    volumes:
      - "./udash/config.yaml:/home/udash/.udash/config.yaml"
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=PathPrefix(`/api/`)"
      - "traefik.http.routers.server.service=server"
      - "traefik.http.services.server.loadbalancer.server.port=8080"

  front:
    image: ghcr.io/updatecli/udash-front:v0.27.1@sha256:b5e8107d6edd5329275cbcd33144d712aeea6c4e958ccc072db3c7e9968854a5
    restart: always
    volumes:
      - "./udash-front/config.json:/usr/share/nginx/html/config.json"
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=PathPrefix(`/`)"
      - "traefik.http.routers.front.service=front"
      - "traefik.http.services.front.loadbalancer.server.port=80"

  traefik:
    image: traefik:v3.7@sha256:24841fe2de7304c149343d877d2923b4c8800a38ba015dea9174c23b20e344a0
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
