---
title: "Compose"
description: "Compose Updatecli policies"
date: 2023-10-01T12:21:01+02:00
draft: false
images: []
menu:
  docs:
    parent: "core"
weight: 130 
toc: true
---
// <!-- Required for asciidoctor -->
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] config key
:toclevels: 4

WARNING: This feature is still in an early stage, Feedback welcome.

== Description

Updatecli compose feature allows to specify a list of Updatecli policies to enforce.

By default, it relies on a file named "update-compose.yaml" such as in the follow example:

.update-compose.yaml
```
policies:
  - policy: ghcr.io/updatecli/policies/golang:v0.0.1
  - policy: ghcr.io/updatecli/policies/dapper:v0.0.2
    values:
     - values.yaml
  - policy: ghcr.io/updatecli/policies/golangci-lint:v0.0.3
```

* Running `updatecli compose apply` would enforce the state defined in each of the policies
* Running `updatecli compose diff` would show the targeted state defined in each of the policies
* Running `updatecli compose show` would show the manifest generated by each of the policies

== Parameters

WIP: Once the Updatecli compose jsonschema is published, we should generate a table with all the available settings

IMPORTANT: Any value files or secrets file specified in the docker-compose.yaml overrides the default values specified by the policy. It's also worth mentioning that deep merge is not supported.

