---
title: "Configuration"
description: "Updatecli must be fed!"
lead: "Updatecli must be fed!"
date: 2020-10-13T15:21:01+02:00
lastmod: 2020-10-13T15:21:01+02:00
draft: false
images: []
menu: 
  docs:
    parent: "core"
weight: 130
toc: true
---
// <!-- Required for asciidoctor -->
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] config key
:toclevels: 4

Updatecli requires a configuration file, or "manifest", which describes the update pipeline.
A manifest describes the "what", the "when", and the "where" of the update pipeline.

**What**

The "what" is the "source" and defines what piece of information we're looking for, such as the latest application release version, a docker image tag, etc.

**When**

The "when" is a "condition", if the condition is satisfied then the target is updated.

**Where**

The "where" is the "target" and defines where we want to update a piece of information like a value from a Dockerfile or YAML file.


== Manifest

=== File

Updatecli expects one file per manifest, or pipeline.
The manifest is split into different stages, "source", "conditions", "targets",
where every stage relies on a plugin to adapt the behavior.

A file can be of type "yaml" or "Go Template" using the file extension ".yaml",".yml", or ".tpl").

Manifests are given to the updatecli command using the global flag `--config <go_template_file>` and `--values <yaml_file>`.
It accepts either a single file or a directory.
If a directory is specified, then it runs recursively on all the go templates (or yaml files) in the directory.


=== Content

Using go templates allows us to specify generic values in a different YAML file, using `--values`.
We then reference those values from each go template.
Updatecli also provides a custom function called `requiredEnv` to inject an environment variable into the template example, `{{ requiredEnv "PATH" }}`. +
Additionally, all functions from the https://masterminds.github.io/sprig/[Sprig template library] are available.

More information on Go templates is https://golang.org/pkg/text/template/[here].

An example values file can contain:

[source,yaml]
----
{{<include "assets/code_example/docs/core/configuration/values.yaml">}}
----

That can used in a pipeline manifest as:

[source,yaml]
----
{{<include "assets/code_example/docs/core/configuration/updatecli.yaml">}}
----

== Go Further

* To know more about Condition syntax link:/docs/core/condition[condition]
* To know more about Source syntax link:/docs/core/source[source]
* To know more about Target syntax link:/docs/core/target[target]
* To know more about link:/plugins/[Plugins]
** More specifically about the link:/plugins/source[source]
** More specifically about the link:/plugins/condition[condition]
** More specifically about the link:/plugins/target[target]
** More specifically about the link:/plugins/scm[SCM]
