---
title: "Git Tag"
description: "Manipulate Git Tag information"
lead: "kind: gittag"
date: 2021-04-08T15:21:01+02:00
lastmod: 2022-03-04T09:57:01+02:00
draft: false
images: []
menu:
  docs:
    parent: "plugin-resource"
weight: 130
toc: true
plugins:
  - source
  - condition
  - target
---
// <!-- Required for asciidoctor -->
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] config key
:toclevels: 4

[cols="1^,1^,1^",options=header]
|===
| source | condition | target
| &#10004; | &#10004; | &#10004;
|===

**source**

The Git Tag "source" retrieves the latest git Tag matching a pattern.

**condition**

The Git Tag "condition" tests if git Tag matching a pattern exist.

**target**

The Git Tag "condition" ensures a git Tag matching a pattern exist otherwise it creates it.

== Parameter

The gittag resource is a resource designed to be used with the scmID

[cols="1,1,1,4",options=header]
|===
| Name | Required | Default |Description
| path | | - | [S,C,T]Define the git directory path, not compatible with scmID
| versionFilter | | | Provide version filtering information
| versionFilter.kind | | "latest" | VersionFilter.kind accept on of the following values: ["semver","latest","regex"]
| versionFilter.pattern | | | The default pattern value depends on the version kind
| message | | "Generated by updatecli" | [T] Defines the tag message
|===


== Example

.updatecli.yaml
```
{{<include "assets/code_example/docs/plugins/gittag/updatecli.yaml">}}

```

include::content/en/docs/plugins/_versionFilter.adoc[]
