---
title: "Jenkins"
description: "Manipulate Jenkins information"
lead: "kind: jenkins"
date: 2021-01-09T15:21:01+02:00
lastmod: 2021-01-09T15:21:01+02:00
draft: false
images: []
menu:
  docs:
    parent: "plugin-resource"
toc: true
plugins:
  - source
  - condition
---

// <!-- Required for asciidoctor -->
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] config key
:toclevels: 4

[cols="1^,1^,1^",options=header]
|===
| source | condition | target
| &#10004; | &#10004; | &#10007;
|===

== Description

**source**

The jenkins "source" retrieves the latest version for a specific Jenkins release

**condition**

The jenkins "condition" test that a version exists and also that the version corresponds to a specific release type


== Parameters

{{< resourceparameters "sources" "jenkins" >}}

How to create a Github Personal Access Token https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token[Doc]

== Example

In the following example, we want to update a valid Jenkins Docker Image tag inside a yaml each time a new jenkins weekly release is published. But before we do, we need to validate few assumptions:

. A valid docker image has been published
. Our infrastructure uses the correct docker image name
. A that the version we are going to install a weekly release

To apply this update strategy, we can run the following command

`updatecli --config updatecli.yaml --values values.yaml`

[source,yaml]
----
# updatecli.yaml
{{<include "assets/code_example/docs/plugins/resources/jenkins/updatecli.d/default.yaml">}}
----

[source,yaml]
----
# updatecli.yaml
{{<include "assets/code_example/docs/plugins/resources/jenkins/values.yaml">}}
----
