---
title: "GitHub Action"
description: "Automate Updatecli with GitHub Action"
lead: "Automate Updatecli with GitHub Action"
date: 2021-01-09T15:21:01+02:00
lastmod: 2021-01-09T15:21:01+02:00
draft: false
images: []
menu: 
  docs:
    parent: "automate"
weight: 130 
toc: true
---
// <!-- Required for asciidoctor -->
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] config key
:toclevels: 4

== Description

Updatecli is most effective when executed regularly and automatically. So, lets see how to use updatecli in a GitHub Action.


== Migration

=== From V1 to v2

The updatecli action v1 was a "GitHub Action" of type docker. While it was easier to start with, that type of GitHub Action runs in a docker container and so in a fully isolated environment.
Updatecli uses many other tools. So switching to a Javascript GitHub action, allows installing updatecli directly on the GitHub Action runner next to those other tools.
Now, the goal of this GitHub action evolved from running updatecli to installing updatecli.

== Parameter

=== Version
`version`: specifies the Updatecli version to install. Accepted values are any valid releases such as `v0.25.0`.
The default value corresponds to the latest Updatecli version

Required: false

== Example

The current example takes uses the repository https://github.com/jenkins-infra/jenkins-infra[jenkins-infra/jenkins-infra].

Once you have your update strategy configuration in the directory `./updatecli/updatecli.d`, you need following files in order to run updatecli from Github Action.

**./updatecli/values.yaml**
```
{{< include "assets/code_example/docs/automate/github_action/values.yaml" >}}
```

**./github/workflows/updatecli.yaml**
```
{{< include "assets/code_example/docs/automate/github_action/updatecli.yaml" >}}
```

IMPORTANT: Environment variables starting with `GITHUB_` are reserved by GitHub Actions.
