---
title: "Guide: Npm"
description: "Automate based on a npm package"
lead: "Automate based on a npm package"
date: 2023-02-07T22:10:01+02:00
draft: false
images: []
menu:
  docs:
    parent: "guide"
weight: 130
toc: true
---
// <!-- Required for asciidoctor -->
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] config key
:toclevels: 4

== npm

==== Goal

The purpose of this pipeline is to track one npm dependency update, and then update both the package.json and package-lock.json in case of a version change.

=== Requirement

This guide requires:

. updatecli
. npm
. IDE
. GitHub Personal Access Token

==== updatecli

{{< updatecli_description >}}

==== IDE

{{< ide_jsonschema >}}

==== npm

npm is a package manager for the Javascript programming language.

==== GitHub PAT

The GitHub PAT, is the token used to authenticate with the GitHub api
link:https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token[Documentation]

=== Pipeline
==== Description

Updatecli relies on one or multiple pipeline manifest to describe the expected Update pipeline.
In this guide, we use the two following components

. A source of kind `npm` to monitor the npm dependency
. A target of kind `shell` to run a command for updating both the 'package-lock.json' and 'package.json'

[source,yaml]
----
#package.json
{{< include "assets/code_example/docs/guides/npm/package.json" >}}
----

==== Manifest

[source,yaml]
----
#updatecli.d/manifest.yaml
{{< include "assets/code_example/docs/guides/npm/updatecli.d/manifest.yaml" >}}
----

Then you can run:

```
export UPDATECLI_GITHUB_TOKEN=<your_PAT>
export UPDATECLI_GITHUB_ACTOR=<your GH username>
updatecli diff --config updatecli.d/manifest.yaml`
```

=== Going further

Once happy with the Update pipeline, you can leverage CI environment to run it regularly. You'll need Updatecli installed in your CI environment, and the right credentials. More information link:https://www.updatecli.io/docs/automate/github_action/[here]

This guide demonstrated a simple update pipeline, but real-world situations usually require either updating all dependencies specified in a package.json, or updating additional resources such as documentation, CI environment, etc.

In the case of updating all dependencies from a package.json at once, the Autodiscovery feature is our current experimentation for addressing the problem. Feel free to reach out as we are still shaping this feature. To see what it looks like you can run `updatecli --experimental` from a repository containing package.json

In the situation of a more tailored update scenario, you may need to extend the current pipeline using additional resources such as:

**Dockerfile**
Adding a target of kind `dockerfile`, Updatecli could update the npm dependency used within a Dockerfile as part of the same operation.

**Yaml**
Adding a target of kind `yaml`, Updatecli could also update the npm dependency used in any yaml as part of the same operation.

Feel free to chat on the Updatecli link:https://matrix.to/#/#Updatecli_community:gitter.im[Matrix] channel.

