---
title: "Github Release"
description: "Manipulate Github release information"
lead: "kind: githubRelease"
date: 2021-01-09T15:21:01+02:00
lastmod: 2021-01-09T15:21:01+02:00
draft: false
images: []
menu: 
  docs:
    parent: "resources"
weight: 130 
toc: true
---
// <!-- Required for asciidoctor -->
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] config key
:toclevels: 4

[cols="1^,1^,1^",options=header]
|===
| source | condition | target
| &#10004; | &#10007; | &#10007;
|===

== Description

**source**

The GitHub Release "source" retrieves the latest release version 

== Parameter

[cols="1,1,1,4",options=header]
|===
| Name | Required | Default |Description
| owner | &#10004; | - | Define Github repository owner
| repository | &#10004; | - | Define Github repository name.
| token | &#10004; | - | Define the token needed to authenticate with the docker registry
| url | | github.com | Define github url
| version | | source output | Define Github Release version.
| versiontype | | semver | Version type. accepted values: ["semver","text"]
|===


=== Version Type
The `version` value can be set to a version pattern and that version pattern has different behaviors depending on the version type. It can either be a simple text value or semantic version compliant, the latter one offers more advanced pattern..

==== Semantic Versionning ["semver"]
link:https://github.com/Masterminds/semver#checking-version-constraints[More information]
If version type is set to "semver" then we assume that we are manipulating version respecting semantic version rules. The version pattern can be specified by the ke `version` as in the following example

**Remark**

In the process we drop any characters not respecting semantic version like in this version "v1.0.0", we drop the "v" but we can added it back using `transformers`.

```
source:
  kind: githubRelease
  spec:
    owner: "jenkins-infra"
    repository: "jenkins-wiki-exporter"
    token: "{{ requiredEnv "ENV_VARIABLE" }}"
    username: "john"
    version: "~1.10"
  transformers:
    - addPrefix: "v"
```
=> Return v1.10.3

==== Text ["text"]
Because not everybody project respects semantic versionning, we can also specify a basic rule, so the pattern would return the latest version return by the github api, starting with a text pattern.

**Remark**:

It's considered a very bad practice to store credentials in an un-encrypted file.
Consider using an environment variable to store the token.

```
source:
  kind: githubRelease
  spec:
    owner: "jenkins-infra"
    repository: "jenkins-wiki-exporter"
    token: "{{ requiredEnv "ENV_VARIABLE" }}"
    username: "john"
    version: "v1.10"
  transformers:
    - addPrefix: "v"
```
=> Return v1.10.3

== Example 


.updatecli.yaml
```
source:
  name: Get Latest helm release version
  kind: githubRelease
  spec:
    owner: "helm"
    repository: "helm"
    token: {{ requiredEnv .github.token }}
    username: olblak
    version: latest
conditions:
  isENVSet:
    name: Is ENV HELM_VERSION set
    kind: dockerfile
    spec:
      file: docker/Dockerfile
      Instruction: ENV[1][0]
      Value: "HELM_VERSION"
    scm:
      github:
        user: "updatecli"
        email: "updatecli@olblak.com"
        owner: "olblak"
        repository: "charts"
        token: {{ requiredEnv "GITHUB_TOKEN" }}
        username: "olblak"
        branch: "master"
targets:
  updateENVHELMVERSION:
    name: Update HELM_VERSION
    kind: dockerfile
    spec:
      file: docker/Dockerfile
      Instruction: ENV[1][1]
    scm:
      github:
        user: "updatecli"
        email: "updatecli@olblak.com"
        owner: "olblak"
        repository: "charts"
        token: {{ requiredEnv "GITHUB_TOKEN" }}
        username: "olblak"
        branch: "master"
```

What it says:

*Source*

Retrieve the latest helm version from its github release located on https://github.com/helm/helm
  => v3.4.2

*Conditions*

Then it tests one condition:
If the dockerfile 'docker/Dockerfile' is located on the git repository https://github.com/olblak/charts 
has the instruction ENV[1][0] set to "HELM_VERSION". ENV[1][0] is a custom syntax to represent 
a two-dimensional array where the first element represents a specific Dockerfile instruction identifier
starting from "0" at the beginning of the document, so we are looking for the second INSTRUCTION "ENV".
The second element represents an instruction argument position. In this case, we want to check that ENV key
is set to "HELM_VERSION"

*Targets*

If the condition is met, which is to be sure that the ENV key set to "HELM_VERSION" exist, then we'll 
are going to update its value if needed based on the version retrieved from the source.
The syntax is the same for the condition excepted that this time we are looking for ENV[1][1]
which means that the second argument of the second ENV instruction.
