---
title: "Helm Chart"
description: "Manipulate Helm Chart information"
lead: "kind: helmChart"
date: 2021-01-09T15:21:01+02:00
lastmod: 2021-01-09T15:21:01+02:00
draft: false
images: []
menu: 
  docs:
    parent: "resources"
weight: 130 
toc: true
---
// <!-- Required for asciidoctor -->
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] config key
:toclevels: 4



[cols="1^,1^,1^",options=header]
|===
| source | condition | target
| &#10004; | &#10004; | &#10007;
|===

**source**

The Helm chart "source" retrieves the latest version of a Helm package.

**condition**

The Helm chart "condition" tests if a helm chart release exist. 

== Parameter

[cols="1,1,1,4",options=header]
|===
| Name | Required | Default |Description
| url  | &#10004; | - | Define url for remote Helm chart repository
| name | &#10004; | - | Define Helm chart package name.
| version | &#10004; | Source | Define Helm chart version.
|===

== Example

.updatecli.yaml
```
source:
  kind: helmChart
  spec:
    url: https://charts.jenkins.io
    name: jenkins
conditions:
  isPrometheuseHelmChartVersionAvailable:
    name: "Test if the prometheus helm chart is available"
    kind: helmChart
    spec:
      url: https://prometheus-community.github.io/helm-charts
      name: prometheus
      version: 11.16.5
  chartVersion:
    name: "jenkinsci/jenkins Helm Chart used"
    kind: yaml
    spec:
      file: "charts/jenkins/requirements.yaml"
      key: "dependencies[0].name"
      value: "jenkins"
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
targets:
  chartVersion:
    name: "jenkinsci/jenkins Helm Chart"
    kind: yaml
    spec:
      file: "charts/jenkins/requirements.yaml"
      key: "dependencies[0].version"
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
```

What it says:

**Source**

Retrieve the version from the Jenkins helm chart repository located on "https://charts.jenkins.io"
  => 2.7.1

**Conditions**

Then it tests two conditions.

. Test a helmchart condition, "Is the prometheus helm chart version "11.16.5" is available from https://prometheus-community.github.io/helm-charts?
  => Yes, proceed, No then abort
. - Test a yaml condition, "Do we have an yaml file named "charts/jenkins/requirements.yaml" with the key dependencies that contains an array where the first element is set to "jenkins" ?"
  => Yes, proceed, No then abort

**Targets**

If conditions are all met, then updatecli will update (if needed) the first element of the key
"dependencies" to "2.7.1" for the file "charts/jenkins/requirements.yaml"
from the github repository olblak/chart then publish changes using a Github Pull Request targeting the master from a temporary branch.

[NOTE]
====
The specificity in this example is that we are using a go template
so we could reuse information accross the yaml file or use environment variable which contains the github token
====
