---
title: "GitHub Actions"
description: "Automate Updatecli with GitHub Action"
lead: "Automate Updatecli with GitHub Action"
date: 2021-01-09T15:21:01+02:00
lastmod: 2021-01-09T15:21:01+02:00
draft: false
images: []
menu: 
  docs:
    parent: "automate"
weight: 130 
toc: true
---
// <!-- Required for asciidoctor -->
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] config key
:toclevels: 4

== Description

Updatecli is better when executed regularly so let see how to use this GitHub Action install Updatecli in your runner.

== Parameter

=== version
`version`: Specify the Updatecli version to install. Accepted values are any valid releases such as "v0.25.0". Default value is set to the latest updatecli version

Required: false

== Example

The current example is inspired from the repository https://github.com/jenkins-infra/jenkins-infra[jenkins-infra/jenkins-infra].

Once you have your update strategy configuration in the directory `./updatecli/updatecli.d`, then you need following files in order to run updatecli from Github Action.

**./updatecli/values.yaml**
```
{{< include "assets/code_example/docs/automate/github_action/values.yaml" >}}
```

**./github/workflows/updatecli.yaml**
```
{{< include "assets/code_example/docs/automate/github_action/updatecli.yaml" >}}
```

IMPORTANT:Environment variables starting with `GITHUB_` are reserved by GitHub Action
