---
title: "Installation"
description: "Give a try to updatecli !"
lead: "Give a try to updatecli !"
date: 2020-10-13T15:21:01+02:00
lastmod: 2022-01-22T08:16:01+02:00
draft: false
images: []
menu: 
  docs:
    parent: "prologue"
weight: 119
toc: true
---

// <!-- Required for asciidoctor -->
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] config key
:toclevels: 4

== Packages

Updatecli is a standalone binary available on https://github.com/updatecli/updatecli/releases/latest[GitHub] with packages for Windows, Linux and OSX.

== macOS via Homebrew

link:https://brew.sh/[Homebrew] is the easiest way to install `updatecli` on macOS. 
See the link:https://brew.sh/[Homebrew documentation] for installation and usage explanations.

First configure the `updatecli` third-party repository (called a link:https://docs.brew.sh/Taps["tap"]) with: 

[source,shell]
----
brew tap updatecli/updatecli
----

Then proceed with the actual installation with:

[source,shell]
----
brew install updatecli
----

To check, later, if a newer version is available, use `brew outdated updatecli`. 
Should you then want to upgrade to the latest version, use `brew upgrade updatecli`.

== Linux

**Opensuse**
[source,shell]
```
# amd64
sudo zypper install https://github.com/updatecli/updatecli/releases/download/v0.38.0/updatecli_amd64.rpm
# arm64
sudo zypper install https://github.com/updatecli/updatecli/releases/download/v0.38.0/updatecli_arm64.rpm
# armv6
sudo zypper install https://github.com/updatecli/updatecli/releases/download/v0.38.0/updatecli_armv6.rpm
```

**Debian/Ubuntu**
[source,shell]
```
# amd64
curl -sL -o/var/cache/apt/archives/updatecli_amd64.deb https://github.com/updatecli/updatecli/releases/download/v0.38.0/updatecli_amd64.deb
# arm64
curl -sL -o/var/cache/apt/archives/updatecli_amd64.deb https://github.com/updatecli/updatecli/releases/download/v0.38.0/updatecli_arm64.deb
# armv6
curl -sL -o/var/cache/apt/archives/updatecli_amd64.deb https://github.com/updatecli/updatecli/releases/download/v0.38.0/updatecli_armv6.deb
```

**Fedora/Centos/RedHat**
[source,shell]
```
# amd64
dnf install https://github.com/updatecli/updatecli/releases/download/v0.38.0/updatecli_amd64.rpm
# arm64
dnf install https://github.com/updatecli/updatecli/releases/download/v0.38.0/updatecli_arm64.rpm
# armv6
dnf install https://github.com/updatecli/updatecli/releases/download/v0.38.0/updatecli_armv6.rpm
```

**Tgz**
[source,shell]
```
# amd64
curl -sL -o/tmp/updatecli_amd64.tgz https://github.com/updatecli/updatecli/releases/download/v0.38.0/updatecli_amd64.tgz
# arm64
curl -sL -o/tmp/updatecli_arm64.tgz https://github.com/updatecli/updatecli/releases/download/v0.38.0/updatecli_arm64.tgz
# armv6
curl -sL -o/tmp/updatecli_armv6.tgz https://github.com/updatecli/updatecli/releases/download/v0.38.0/updatecli_armv6.tgz
```

== Docker
A docker image is also available on:

* https://github.com/users/updatecli/packages/container/package/updatecli[ghcr.io/updatecli/updatecli]
* https://hub.docker.com/r/updatecli/updatecli[updatecli/updatecli] 

Remark: Because of the limits on DockerHub free account, it's better to use the ghcr.io image.

=== Usage

```
 docker run -i -t -v "$PWD/updateCli.yaml":/updatecli/updateCli.yaml:ro ghcr.io/updatecli/updatecli:latest diff --config /updatecli/updateCli.yaml

 docker run -i -t -v "$PWD/updateCli.yaml":/updatecli/updateCli.yaml:ro ghcr.io/updatecli/updatecli:latest apply --config /updatecli/updateCli.yaml

 docker run -i -t ghcr.io/updatecli/updatecli:latest help
```
