---
title: "Git"
description: "Interact with git repositories"
lead: "kind: git"
date: 2021-01-09T15:21:01+02:00
lastmod: 2021-05-02T20:44:01+02:00
draft: false
images: []
menu: 
  docs:
    parent: "plugins"
weight: 130 
toc: true
plugins:
  - scm
---
// <!-- Required for asciidoctor -->
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] config key
:toclevels: 4

== Description

The "scm" of kind `git`, defines parameters to interact with a git repository. It is then referenced from another "resource" by using the key `scmID`.
Depending on the resource that referenced the git configuration, the behavior will change.

**source**

When a source resource references a scm configuration, then it usually means using a file from that repository.

**condition**

When a condition references a scm configuration, then it usually means using a file from that repository.

**target**

When a target references a scm configuration, it usually means pushing file to that repository.

== Parameters

[cols="1,1,1,4",options=header]
|===
| Name | Required | Default |Description
| url | &#10004; | | Define Git repository url, username and password can't be embedded inside the url as it's not supported, instead use specific username/password settings
| username | | | Define the username used to authenticate with the git repository
| password | | | Define the password used to authenticate with the git repository
| branch | &#10004; | master | Define the git branch
| user | | | Define Git user used by git config
| email | | | Define Git email used by the git config
| force | | false | Run git push using --force option
| directory | |Default to tmp location, /tmp on linux | Define where to clone the git repository
| commitMessage | | | [T] Customize commit message. More information link:#_commitmessage[here]
| gpg | | | [T] Sign commit with a GPG key. More information link:#_gpg[here]
|===

=== GPG

Updatecli can sign commits using a private GPG key if configured accordingly.

---
[cols="1,1,1,4",options=header]
|===
| Name | Required | Default |Description
| signingkey ||| Defines the armored private gpg key
| password ||| Defines the gpg key password
|===


=== CommitMessage

Updatecli uses conventional commits as describe on link:https://www.conventionalcommits.org/[www.conventionnalcommits.org]. +
The goal is to add human and machine readable meaning to commit messages

By default, Updatecli generates a commit message using the default type "chore" and split long title message into the body like:

---
```
Author: olblak <updatecli@updatecli.io>
Date:   Tue May 4 15:41:44 2021 +0200

    chore: Update key "dependencies[0].version" from file "charts/jenkins/r...

    ... equirements.yaml"

    Made with ❤️️  by updatecli
```
---


[cols="1,1,1,4",options=header]
|===
| Name | Required | Default |Description
|type ||chore| Specify commit type
|scope ||| Specify commit scope
|footer ||| Specify commit footer message
|title ||| Override default body message
|hideCredit ||| Remove "Made with ❤️️  by updatecli" from commit message body
|body ||| Override default body message
|===

=== Authentication

At the moment they are two ways to authentication with a git repository, either using a `username`/`password`` from the updatecli configuration, or relying on the local ssh-agent.

== Example

**updatecli.yaml**
```
{{< include "assets/code_example/docs/plugins/git/updatecli.yaml" >}}
```
