---
title: "Git Tag"
description: "Manipulate Git Tag information"
lead: "kind: gitTag"
date: 2021-04-08T15:21:01+02:00
lastmod: 2021-04-08T15:21:01+02:00
draft: false
images: []
menu:
  docs:
    parent: "plugins"
weight: 130
toc: true
plugins:
  - source
  - condition
  - target
---
// <!-- Required for asciidoctor -->
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] config key
:toclevels: 4

[cols="1^,1^,1^",options=header]
|===
| source | condition | target
| &#10004; | &#10004; | &#10004;
|===

**source**

The Git Tag "source" retrieves the latest git Tag matching a pattern.

**condition**

The Git Tag "condition" tests if git Tag matching a pattern exist.

**target**

The Git Tag "condition" ensures a git Tag matching a pattern exist otherwise it creates it.

== Parameter

The gittag resource is a resource designed to be used with the scmID

[cols="1,1,1,4",options=header]
|===
| Name | Required | Default |Description
| path | | - | [S,C,T]Define the git directory path, not compatible with scmID
| versionFilter | | | [S,C] Define the tag "version" pattern
| message | | "Generated by updatecli" | [T] Defines the tag message
|===

The git tag

=== Version Filter

The resource `gittag` support versionFilter parameters.

include::content/docs/plugins/_versionFilter.adoc[]

== Example

.updatecli.yaml
```
{{<include "assets/code_example/doc/plugins/gittag/updatecli.yaml">}}

```
