---
title: "Bitbucket Server (Stash) "
description: "Interact with Bitbucket Server (Stash) repositories"
lead: "Stash scm"
date: 2022-07-25T18:31:01+02:00
draft: false
images: []
menu:
  docs:
    parent: "plugin-scm"
toc: true
plugins:
  - scm
---

// <!-- Required for asciidoctor -->
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] config key
:toclevels: 4

== Description

The Bitbucket Server (Stash) scm plugin is used to manage git repositories hosted on Bitbucket Server (Stash), depending on the stage, it can be used for different purposes

**source**: Retrieve data from a git repository, such as a file content
**condition**: Ensure data exist on a git repository, such as a file content
**target**: Ensure data is up to date on a git repository

== Parameters

{{< resourceparameters "scms" "stash" >}}

=== CommitMessage

Updatecli uses conventional commits as describe on link:https://www.conventionalcommits.org/[www.conventionnalcommits.org]. +
The goal is to add human and machine readable meaning to commit messages

By default, Updatecli generates a commit message using the default type "chore" and split long title message into the body like:

---
```
Author: olblak <updatecli@updatecli.io>
Date:   Tue May 4 15:41:44 2021 +0200

    chore: Update key "dependencies[0].version" from file "charts/jenkins/r...

    ... equirements.yaml"

    Made with ❤️️  by updatecli
```
---


[cols="1,1,1,4",options=header]
|===
| Name | Required | Default |Description
|type ||chore| Specify commit type
|scope ||| Specify commit scope
|footer ||| Specify commit footer message
|title ||| Override default body message
|hideCredit ||| Remove "Made with ❤️️  by updatecli" from commit message
|body ||| Override default body message
|===

=== GPG

Updatecli can sign commits using a private GPG key if configured accordingly.

---
[cols="1,1,1,4",options=header]
|===
| Name | Required | Default |Description
| signingkey ||| Defines the armored private gpg key 
| password ||| Defines the gpg key password
|===


== Example

[source,yaml]
----
# updatecli.yaml
{{<include "assets/code_example/docs/plugins/stash/updatecli.yaml">}}
----

=== Performance on large repositories

By default, Updatecli fetches every branch, tag, and other ref from the remote repository, which can be slow on repositories with a large number of refs (hundreds of branches/tags, hundreds of thousands of commits).

Setting `depth` to a low value (e.g. `1`) combined with `singleBranch: true` restricts the checkout to the configured `branch` only, skipping the fetch of every other branch, tag, and ref on the remote. This can drastically reduce checkout time on large repositories.

NOTE: Enabling `singleBranch` means Updatecli only has visibility into the configured branch. If your pipeline relies on detecting other branches or tags (for example to avoid opening duplicate pull requests), keep this option disabled.

[source,yaml]
----
# updatecli.yaml
{{<include "assets/code_example/docs/plugins/stash/updatecli-performance.yaml">}}
----

