name: Example 2

sources:
  jenkins:
    kind: dockerdigest
    spec:
      image: "jenkins/jenkins"
      tag: "lts-jdk11"
      architecture: "amd64"

targets:
  imageTag:
    name: "jenkins/jenkins:lts-jdk11 docker digest"
    kind: yaml
    transformers:
      - addprefix: "jenkins/jenkins@sha256:"
    spec:
      file: "./docker-compose.yaml"
      key: "services.jenkins.image"
