name: Example 1

sources:
  jenkins:
    name: "Get latest Jenkins version from maven repo"
    kind: maven
    transformers:
      # - addprefix: "v"
      - addsuffix: "-jdk11"
    spec:
      url: "repo.jenkins-ci.org"
      repository: "releases"
      groupid: "org.jenkins-ci.main"
      artifactid: "jenkins-war"

conditions:
  docker:
    name: "Docker Image Published on Registry"
    kind: dockerimage
    spec:
      image: "jenkins/jenkins"
      architecture: "amd64"

targets:
  imageTag:
    name: "Update docker-compose jenkins service"
    kind: yaml
    transformers:
      - addprefix: "jenkins/jenkins:"
    spec:
      file: "./docker-compose.yaml"
      key: "services.jenkins.image"
