---
name: Updatecli - Release
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run at 12:00 every Thursday
    - cron: "0 12 * * 4"
  repository_dispatch:
    types:
      - "updatecli-release"
permissions: {}
jobs:
  updatecli:
    name: "Updatecli - ${{ matrix.target_name }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - target_name: "release pipelines"
            apply_args: "--file updatecli-compose-release.yaml"
          - target_name: "updatecli release"
            apply_args: "--labels=release:updatecli"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          persist-credentials: false
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@5dfc616e57b07d2302c3f37e5b72a4ead82dbbf8" # v3.4.0
        with:
          version: "v0.119.0"
      # releasepost is required by the Updatecli
      #   * policy ghcr.io/updatecli/policies/releasepost/releasepost
      - name: "Install Releasepost"
        uses: "updatecli/releasepost-action@864390bddae97db06ee881ab4a08d159b4464643" # v0.5.0
      - name: "Run updatecli"
        run: updatecli compose apply --clean-git-branches=true ${{ matrix.apply_args }} --experimental
        env:
          UPDATECLI_GITHUB_APP_CLIENT_ID: ${{ secrets.UPDATECLIBOT_APP_ID }}
          UPDATECLI_GITHUB_APP_PRIVATE_KEY: ${{ secrets.UPDATECLIBOT_APP_PRIVKEY }}
          UPDATECLI_GITHUB_APP_INSTALLATION_ID: ${{ secrets.UPDATECLIBOT_APP_INSTALLATION_ID }}
          UPDATECLI_UDASH_API_URL: ${{ secrets.UPDATECLI_UDASH_API_URL }}
          UPDATECLI_UDASH_ACCESS_TOKEN: ${{ secrets.UPDATECLI_UDASH_ACCESS_TOKEN }}
          UPDATECLI_UDASH_URL: ${{ secrets.UPDATECLI_UDASH_URL }}
          RELEASEPOST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
